export const SIGNUP_SAVE_INPUT = 'SIGNUP_SAVE_INPUT';
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const LOGIN_SAVE_INPUT = 'LOGIN_SAVE_INPUT';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const NEW_ENTRY_SAVE_INPUT = 'NEW_ENTRY_SAVE_INPUT';
export const NEW_ENTRY_REQUEST = 'NEW_ENTRY_REQUEST';
export const NEW_ENTRY_SUCCESS = 'NEW_ENTRY_SUCCESS';
export const NEW_ENTRY_FAILURE = 'NEW_ENTRY_FAILURE';

export const FETCH_ENTRIES_REQUEST = 'FETCH_ENTRIES_REQUEST';
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS';
export const FETCH_ENTRIES_FAILURE = 'FETCH_ENTRIES_FAILURE';
